// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBH4nhPv6W8BYu4eMBkb1BcORmeoaxhzs',
    appId: '1:1097975574150:web:37c4ad6494f04711a22b07',
    messagingSenderId: '1097975574150',
    projectId: 'rubricamovil-f9e8b',
    authDomain: 'rubricamovil-f9e8b.firebaseapp.com',
    storageBucket: 'rubricamovil-f9e8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkkplUMspCcuyWUqL3CqSRQNzASBXydgI',
    appId: '1:1097975574150:android:686ad14483b62027a22b07',
    messagingSenderId: '1097975574150',
    projectId: 'rubricamovil-f9e8b',
    storageBucket: 'rubricamovil-f9e8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmhvbsmmdRLRyboFC95yLCMN38Y-txUIo',
    appId: '1:1097975574150:ios:08fbbd74587b69d9a22b07',
    messagingSenderId: '1097975574150',
    projectId: 'rubricamovil-f9e8b',
    storageBucket: 'rubricamovil-f9e8b.appspot.com',
    iosBundleId: 'com.example.rubricatres',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmhvbsmmdRLRyboFC95yLCMN38Y-txUIo',
    appId: '1:1097975574150:ios:08fbbd74587b69d9a22b07',
    messagingSenderId: '1097975574150',
    projectId: 'rubricamovil-f9e8b',
    storageBucket: 'rubricamovil-f9e8b.appspot.com',
    iosBundleId: 'com.example.rubricatres',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBH4nhPv6W8BYu4eMBkb1BcORmeoaxhzs',
    appId: '1:1097975574150:web:721f2cff53655eeaa22b07',
    messagingSenderId: '1097975574150',
    projectId: 'rubricamovil-f9e8b',
    authDomain: 'rubricamovil-f9e8b.firebaseapp.com',
    storageBucket: 'rubricamovil-f9e8b.appspot.com',
  );
}
